import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Trans } from "@lingui/react";
import { useState } from "react";

import { loadTranslation } from "../utils";

import classes from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [name, setName] = useState("joe");

  return (
    <>
      <Head>
        <title>static-ws-template</title>
        <meta
          name="description"
          content="A static ws template generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={classes.main}>
        <p>
          <Trans id="Hello {name}" values={{ name }} />
        </p>
      </main>
    </>
  );
};

export const getStaticProps: GetStaticProps = async (ctx) => {
  const translation = await loadTranslation(
    ctx.locale!,
    process.env.NODE_ENV === "production"
  );

  return {
    props: {
      translation,
    },
  };
};

export default Home;
